pub mod color_space;
pub mod colorizer;
pub mod curve;
pub mod gradient;
pub mod lighting_params;
pub mod palette;
pub mod pipeline;
pub mod render_settings;
pub mod shading;
pub mod smooth_iteration;

pub use colorizer::{Colorizer, ColorizerKind};
pub use curve::{Curve, CurvePoint};
pub use gradient::{ColorStop, Gradient};
pub use lighting_params::LightingParams;
pub use palette::{Palette, PaletteLut};
pub use pipeline::ColorPipeline;
pub use render_settings::RenderSettings;
pub use shading::apply_slope_shading;
pub use smooth_iteration::{SmoothIterationColorizer, SmoothIterationContext};
